# Generated by Django 4.2.23 on 2025-09-13 04:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Required for CREATE INDEX CONCURRENTLY

    dependencies = [
        ("annotations", "0035_remove_metadata_fields"),
    ]

    operations = [
        # Covering index for annotation queries
        # Rationale: Most queries filter by document, page, and corpus
        # INCLUDE clause includes only small fields to avoid size limits
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_annotation_full_cover
            ON annotations_annotation(document_id, corpus_id, page, structural, analysis_id)
            INCLUDE (annotation_label_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_annotation_full_cover;"
        ),

        # Partial index for structural annotations
        # Rationale: Structural annotations are queried separately and are only ~5% of data
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_annotation_structural
            ON annotations_annotation(document_id)
            WHERE structural = true;
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_annotation_structural;"
        ),

        # Index for corpus-specific non-structural annotations
        # Rationale: Most queries filter out structural annotations
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_annotation_corpus_analysis
            ON annotations_annotation(corpus_id, analysis_id)
            WHERE structural = false;
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_annotation_corpus_analysis;"
        ),

        # Composite index for relationships
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_relationship_corpus_analysis
            ON annotations_relationship(corpus_id, analysis_id, structural);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_relationship_corpus_analysis;"
        ),

        # Index for document relationships with both source and target
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_docrelationship_source_target
            ON documents_documentrelationship(source_document_id, target_document_id, corpus_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_docrelationship_source_target;"
        ),

        # Index for notes
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_note_document_corpus
            ON annotations_note(document_id, corpus_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_note_document_corpus;"
        ),
    ]
