# Generated by Django 4.2.23 on 2025-09-13 04:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Required for CREATE INDEX operations

    dependencies = [
        ("annotations", "0036_add_performance_indexes"),
    ]

    operations = [
        # Document annotation summary
        # Purpose: Pre-aggregate annotation counts and page lists
        # Refresh: On annotation create/update/delete
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS document_annotation_summary AS
            SELECT
                document_id,
                corpus_id,
                COUNT(*) as total_annotations,
                COUNT(*) FILTER (WHERE structural = true) as structural_count,
                COUNT(*) FILTER (WHERE structural = false) as corpus_count,
                COUNT(*) FILTER (WHERE analysis_id IS NULL) as user_annotation_count,
                COUNT(*) FILTER (WHERE analysis_id IS NOT NULL) as analysis_annotation_count,
                COUNT(DISTINCT page) as pages_with_annotations,
                array_agg(DISTINCT page ORDER BY page) as annotated_pages,
                NULL::jsonb as page_details,  -- Simplified to avoid nested aggregates
                MAX(modified) as last_updated
            FROM annotations_annotation
            GROUP BY document_id, corpus_id;

            CREATE UNIQUE INDEX ON document_annotation_summary(document_id, corpus_id);
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS document_annotation_summary;"
        ),

        # Page-level annotation index
        # Purpose: Quick lookup of annotations by page
        # Refresh: On annotation changes for specific pages
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS page_annotation_index AS
            SELECT
                document_id,
                corpus_id,
                page,
                array_agg(
                    json_build_object(
                        'id', id,
                        'label_id', annotation_label_id,
                        'structural', structural,
                        'bbox', bounding_box,
                        'text_preview', LEFT(raw_text, 50)
                    ) ORDER BY id
                ) as annotations
            FROM annotations_annotation
            GROUP BY document_id, corpus_id, page;

            CREATE INDEX ON page_annotation_index(document_id, corpus_id, page);
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS page_annotation_index;"
        ),

        # Label usage statistics
        # Purpose: Quick label filtering and statistics
        # Refresh: Daily or on-demand
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS label_usage_stats AS
            SELECT
                corpus_id,
                annotation_label_id,
                COUNT(*) as usage_count,
                COUNT(DISTINCT document_id) as document_count,
                array_agg(DISTINCT document_id) as document_ids
            FROM annotations_annotation
            WHERE structural = false
            GROUP BY corpus_id, annotation_label_id;

            CREATE INDEX ON label_usage_stats(corpus_id, annotation_label_id);
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS label_usage_stats;"
        ),
    ]
